Repository KinsonDigital/Velaptor, pull requests merged in 2022-11, with the labels that each got.

#418 🚧Setup stale bot
  .github/stale.yml
Labels: workflow, high priority, preview

#421 🚧Update to new logo
  Documentation/Images/velaptor-logo.png
  Velaptor/velaptor-logo.ico
Labels: low priority, preview, 📝documentation/product

#417 🚧Refactor WindowSizeEventArgs ctor param data types
  Testing/VelaptorTests/OpenGL/WindowSizeEventArgsTests.cs
  Velaptor/OpenGL/WindowSizeEventArgs.cs
Labels: good first issue, low priority, preview, 🧨breaking changes, 🍺hacktoberfest-easy

#424 🚧Add total nuget downloads badge
  README.md
Labels: low priority, preview, 📝documentation/product

#425 🚧Add tweet template to project
  .config/dotnet-tools.json
  .github/ReleaseTweetTemplate.txt
Labels: workflow, low priority, preview

#428 🚧Improve discord badge
  README.md
Labels: medium priority, preview, 📝documentation/product

#427 Improve ReadMe
  CONTRIBUTING.md
  README.md
Labels: good first issue, low priority, preview, 📝documentation/product

#429 🚧Refactor code docs
  .editorconfig
  Testing/VelaptorTests/Content/AtlasDataTests.cs
  Testing/VelaptorTests/Content/AtlasLoaderTests.cs
  Testing/VelaptorTests/Content/ContentLoaderTests.cs
  Testing/VelaptorTests/Content/Fonts/WindowsFontPathResolverTests.cs
  Testing/VelaptorTests/Content/TextureFactoryTests.cs
  Testing/VelaptorTests/Content/TextureLoaderTests.cs
  Testing/VelaptorTests/Content/TextureTests.cs
  Testing/VelaptorTests/Input/KeyboardTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
  Testing/VelaptorTests/InternalExtensionMethodsTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/BufferManagerTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/FontGPUBufferTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/GPUBufferBaseTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/RectGPUBufferTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/TextureGPUBufferTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/OpenGL/Services/ShaderTemplateProcessorServiceTests.cs
  Testing/VelaptorTests/OpenGL/Services/TextureShaderResourceLoaderServiceTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderManagerTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderProgramTests.cs
  Testing/VelaptorTests/UI/ButtonTests.cs
  Testing/VelaptorTests/UI/ControlBaseTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor.sln.DotSettings
  Velaptor/Content/AtlasData.cs
  Velaptor/Content/AtlasJSONDataPathResolver.cs
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/ContentLoader.cs
  Velaptor/Content/IAtlasData.cs
  Velaptor/Content/IContentLoader.cs
  Velaptor/Factories/App.cs
  Velaptor/Factories/AppInputFactory.cs
  Velaptor/Factories/ContentLoaderFactory.cs
  Velaptor/Factories/GPUBufferFactory.cs
  Velaptor/Factories/IGPUBufferFactory.cs
  Velaptor/Guards/EnsureThat.cs
  Velaptor/InternalExtensionMethods.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/PublicExtensionMethods.cs
  Velaptor/Services/AppSettingsService.cs
  Velaptor/Services/BatchServiceManager.cs
  Velaptor/Services/EventLoggerService.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/Services/FontGlyphBatchingService.cs
  Velaptor/Services/IBatchServiceManager.cs
  Velaptor/Services/IFontAtlasService.cs
  Velaptor/Services/IImageService.cs
  Velaptor/UI/Button.cs
  Velaptor/UI/TextBox.cs
  Velaptor/Velaptor.csproj
Labels: 📑documentation/code, good first issue, low priority, preview

#430 🚧Add README to NuGet package
  .config/dotnet-tools.json
  .nuke/parameters.json
  Documentation/Images/twitter-logo-16x16.svg
  LICENSE.md
  README.md
  Velaptor/Velaptor.csproj
Labels: good first issue, medium priority, preview, 📝documentation/product

#436 🚧Increase spacing between buttons on rect scene
  Testing/VelaptorTesting/Scenes/TestRectangleScene.cs
Labels: good first issue, low priority, preview

#439 🚧Update README
  README.md
Labels: good first issue, low priority, preview, 📝documentation/product

#442 🚧Demo video changes
  Documentation/DemoVideo.mp4
  README.md
Labels: high priority, preview, 📝documentation/product
