Repository KinsonDigital/Velaptor, pull requests merged in 2022-12, with the labels that each got.

#453 🚧Refactor unit test assertions
  Testing/VelaptorTests/Content/Fonts/FontLoaderTests.cs
  Testing/VelaptorTests/Content/Fonts/FontPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/FontStatsTests.cs
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Content/Fonts/WindowsFontPathResolverTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/Velaptor.csproj
Labels: tech debt, medium priority, preview

#456 🚧Fix broken logo link in README
  README.md
Labels: high priority, preview, 📝documentation/product

#462 🚧Update project to dotnet 7 & latest C# version
  .run/VelaptorTesting.run.xml
  Testing/VelaptorTesting/VelaptorTesting.csproj
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Graphics/RendererTests.cs
  Testing/VelaptorTests/Guards/EnsureThatTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GLFWMonitorsTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/Fonts/Services/FontService.cs
  Velaptor/Content/Fonts/Services/IFontService.cs
  Velaptor/Graphics/Renderer.cs
  Velaptor/Guards/EnsureThat.cs
  Velaptor/NativeInterop/FreeType/IFreeTypeInvoker.cs
  Velaptor/NativeInterop/GLFW/GLFWInvoker.cs
  Velaptor/NativeInterop/GLFW/GLFWMonitors.cs
  Velaptor/NativeInterop/GLFW/IGLFWInvoker.cs
  Velaptor/OpenGL/Enums.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/Velaptor.csproj
Labels: tech debt, high priority, preview

#463 🚧Fix README broken logo link
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.10.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.11.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.13.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.14.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.3.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.7.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.8.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.9.md
  README.md
  Velaptor/Velaptor.csproj
Labels: high priority, preview, 📝documentation/product

#464 🚧Reduce font allocations and improve perf
  README.md
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTests/InternalExtensionMethodsTests.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Graphics/Renderer.cs
  Velaptor/InternalExtensionMethods.cs
Labels: tech debt, medium priority, preview

#465 🚧Refactor unit test assertions
  Testing/VelaptorTests/Helpers/AssertExtensions.cs
  Testing/VelaptorTests/Services/TextureBatchingServiceTests.cs
  Testing/VelaptorTests/UI/ButtonTests.cs
  Testing/VelaptorTests/UI/ControlBaseTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Testing/VelaptorTests/UI/MousePositionEventArgsTests.cs
Labels: tech debt, medium priority, preview

#466 🚀Preview Release
  .run/VelaptorTesting.run.xml
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.10.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.11.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.13.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.14.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.15.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.3.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.7.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.8.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.9.md
  README.md
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTesting/VelaptorTesting.csproj
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Graphics/RendererTests.cs
  Testing/VelaptorTests/Guards/EnsureThatTests.cs
  Testing/VelaptorTests/Helpers/AssertExtensions.cs
  Testing/VelaptorTests/InternalExtensionMethodsTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GLFWMonitorsTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Testing/VelaptorTests/Services/TextureBatchingServiceTests.cs
  Testing/VelaptorTests/UI/ButtonTests.cs
  Testing/VelaptorTests/UI/ControlBaseTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Testing/VelaptorTests/UI/MousePositionEventArgsTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/Fonts/Services/FontService.cs
  Velaptor/Content/Fonts/Services/IFontService.cs
  Velaptor/Graphics/Renderer.cs
  Velaptor/Guards/EnsureThat.cs
  Velaptor/InternalExtensionMethods.cs
  Velaptor/NativeInterop/FreeType/IFreeTypeInvoker.cs
  Velaptor/NativeInterop/GLFW/GLFWInvoker.cs
  Velaptor/NativeInterop/GLFW/GLFWMonitors.cs
  Velaptor/NativeInterop/GLFW/IGLFWInvoker.cs
  Velaptor/OpenGL/Enums.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#475 🚧Update CICD tool
  .config/dotnet-tools.json
Labels: workflow, high priority, preview

#476 🚧Update System.IO.Abstractions nuget package
  Testing/VelaptorTests/Content/Fonts/FontLoaderTests.cs
  Testing/VelaptorTests/Fakes/ContentPathResolverFake.cs
  Testing/VelaptorTests/Fakes/FileSystemStreamFake.cs
  Testing/VelaptorTests/Fakes/GPUBufferFake.cs
  Testing/VelaptorTests/Fakes/ShaderProgramFake.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor.sln.DotSettings
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/Content/Fonts/Services/FontStatsService.cs
  Velaptor/Content/ISound.cs
  Velaptor/Content/Sound.cs
  Velaptor/Velaptor.csproj
Labels: dependency update, medium priority, preview

#477 🚧Improve release notes grammar and spelling
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.10.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.13.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.14.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.15.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.3.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.9.md
Labels: low priority, preview, 📝documentation/product

#480 🚧Update checkout actions
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
Labels: workflow, high priority, preview

#484 🚧Move internal visible setup
  Velaptor/ExposedInternals.cs
  Velaptor/Velaptor.csproj
Labels: tech debt, low priority, preview
