Repository KinsonDigital/Velaptor, pull requests merged in 2022-10, with the labels that each got.

#381 Remove Mouse Scroll Speed
  Testing/VelaptorTesting/Scenes/TestMouseScene.cs
Labels: good first issue, tech debt, low priority, preview, 🍺hacktoberfest-easy

#379 🚧Change build system
  .config/dotnet-tools.json
  .github/workflows/build-pr-status-check.yml
  .github/workflows/build-status-check.yml
  .github/workflows/feature-pr-branches-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/ignore-build-status-check.yml
  .github/workflows/ignore-unit-testing-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/preview-qa-release.yml
  .github/workflows/preview-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/qa-prod-releases.yml
  .github/workflows/tag-does-not-exist-status-check.yml
  .github/workflows/triage-issue.yml
  .github/workflows/unit-test-pr-status-check.yml
  .github/workflows/unit-testing-status-check.yml
  .github/workflows/validate-preview-release-branches-status-check.yml.disabled
  .github/workflows/validate-prod-release-branches-status-check.yml.disabled
  .github/workflows/version-status-check.yml
  .gitignore
  .nuke/parameters.json
  .vscode/settings.json
  Testing/VelaptorTesting/VelaptorTesting.csproj
  Velaptor.sln
Labels: workflow, tech debt, high priority, preview

#383 🚧Fix pathing issues
  Testing/VelaptorTesting/Scenes/TestMouseScene.cs
  Testing/VelaptorTesting/Scenes/TestNonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/TestRenderTextScene.cs
  Testing/VelaptorTests/Content/AtlasDataTests.cs
  Testing/VelaptorTests/Content/AtlasJSONDataPathResolverTests.cs
  Testing/VelaptorTests/Content/AtlasLoaderTests.cs
  Testing/VelaptorTests/Content/Caching/SoundCacheTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/ContentPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/ContentFontPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/FontLoaderTests.cs
  Testing/VelaptorTests/Content/Fonts/FontStatsTests.cs
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Content/Fonts/WindowsFontPathResolverTests.cs
  Testing/VelaptorTests/Content/SoundPathResolverTests.cs
  Testing/VelaptorTests/Content/TextureLoaderTests.cs
  Testing/VelaptorTests/Content/TexturePathResolverTests.cs
  Testing/VelaptorTests/Graphics/RendererTests.cs
  Testing/VelaptorTests/Helpers/AssertExtensions.cs
  Testing/VelaptorTests/Helpers/TestDataLoader.cs
  Testing/VelaptorTests/Helpers/TestHelpers.cs
  Testing/VelaptorTests/Helpers/TheoryForLinux.cs
  Testing/VelaptorTests/Helpers/TheoryForWindows.cs
  Testing/VelaptorTests/InternalExtensionMethodsTests.cs
  Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/BufferManagerTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/RectGPUBufferTests.cs
  Testing/VelaptorTests/OpenGL/FontGlyphBatchItemTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderManagerTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderProgramTests.cs
  Testing/VelaptorTests/OpenGL/TextureBatchItemTests.cs
  Testing/VelaptorTests/PublicExtensionMethodsTests.cs
  Testing/VelaptorTests/Services/BatchServiceManagerTests.cs
  Testing/VelaptorTests/Services/FontMetaDataParserTests.cs
  Testing/VelaptorTests/Services/ImageServiceTests.cs
  Velaptor/AppStats.cs
  Velaptor/Content/AtlasData.cs
  Velaptor/Content/AtlasJSONDataPathResolver.cs
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/Caching/SoundCache.cs
  Velaptor/Content/Caching/TextureCache.cs
  Velaptor/Content/ContentPathResolver.cs
  Velaptor/Content/Fonts/ContentFontPathResolver.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/Content/Fonts/WindowsFontPathResolver.cs
  Velaptor/Content/SoundPathResolver.cs
  Velaptor/Content/TexturePathResolver.cs
  Velaptor/Factories/AppInputFactory.cs
  Velaptor/Graphics/Renderer.cs
  Velaptor/InternalExtensionMethods.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/OpenGL/Shaders/ShaderProgram.cs
  Velaptor/PublicExtensionMethods.cs
Labels: 🐛bug, high priority, preview

#386 🚧Fix bug with path resolvers
  Testing/VelaptorTests/Content/Fonts/WindowsFontPathResolverTests.cs
  Testing/VelaptorTests/InternalExtensionMethodsTests.cs
  Velaptor/Content/AtlasJSONDataPathResolver.cs
  Velaptor/Content/Fonts/ContentFontPathResolver.cs
  Velaptor/Content/Fonts/FontPathResolver.cs
  Velaptor/Content/Fonts/WindowsFontPathResolver.cs
  Velaptor/Content/SoundPathResolver.cs
  Velaptor/Content/TexturePathResolver.cs
  Velaptor/Factories/PathResolverFactory.cs
  Velaptor/Hardware/SystemMonitor.cs
  Velaptor/InternalExtensionMethods.cs
  Velaptor/NativeInterop/GLFW/GLFWMonitors.cs
  Velaptor/OpenGL/GLWindow.cs
Labels: 🐛bug, high priority, preview

#399 🚧Start process of implementing Fluent Assertions
  Testing/VelaptorTests/VelaptorTests.csproj
Labels: tech debt, high priority, preview

#400 🚧Create system for logging errors, warnings, and events
  Testing/VelaptorTests/AppSettingsTests.cs
  Testing/VelaptorTests/Helpers/FactForDebugAttribute.cs
  Testing/VelaptorTests/Helpers/FactForReleaseAttribute.cs
  Testing/VelaptorTests/Helpers/TheoryForLinux.cs
  Testing/VelaptorTests/Helpers/TheoryForLinuxAttribute.cs
  Testing/VelaptorTests/Helpers/TheoryForWindows.cs
  Testing/VelaptorTests/Helpers/TheoryForWindowsAttribute.cs
  Testing/VelaptorTests/Services/AppSettingsServiceTests.cs
  Testing/VelaptorTests/Services/EventLoggerServiceTests.cs
  Testing/VelaptorTests/Services/LoggingServiceTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/AppSettings.cs
  Velaptor/Content/Fonts/ContentFontPathResolver.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/Content/Fonts/FontPathResolver.cs
  Velaptor/Content/Fonts/Services/FontStatsService.cs
  Velaptor/Content/Fonts/WindowsFontPathResolver.cs
  Velaptor/Factories/App.cs
  Velaptor/IoC.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/Services/AppSettingsService.cs
  Velaptor/Services/ConsoleLoggerService.cs
  Velaptor/Services/ConsoleService.cs
  Velaptor/Services/DateTimeService.cs
  Velaptor/Services/EventLoggerService.cs
  Velaptor/Services/FileLoggerService.cs
  Velaptor/Services/IAppSettingsService.cs
  Velaptor/Services/IConsoleLoggerService.cs
  Velaptor/Services/IConsoleService.cs
  Velaptor/Services/IDateTimeService.cs
  Velaptor/Services/IEventLoggerService.cs
  Velaptor/Services/IFileLoggerService.cs
  Velaptor/Services/ILoggingService.cs
  Velaptor/Services/LoggingService.cs
  Velaptor/Velaptor.csproj
Labels: ✨new feature, high priority, preview

#402 🚧Refactor unit test assertions
  Testing/VelaptorTests/OpenGL/WindowSizeEventArgsTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
Labels: tech debt, low priority, preview, 🍺hacktoberfest-easy

#409 🚧Create outside contributor docs
  .vscode/settings.json
  CONTRIBUTING.md
  Documentation/Branching.md
  Documentation/Images/create-fork.jpg
  README.md
Labels: high priority, preview, 📝documentation/product

#415 🚧Update NVorbis NuGet package
  Velaptor/Velaptor.csproj
Labels: good first issue, dependency update, low priority, preview, 🍺hacktoberfest-easy

#416 🚧Remove library copy in csproj
  Testing/VelaptorTesting/VelaptorTesting.csproj
Labels: good first issue, tech debt, preview, 🍺hacktoberfest-easy
