Repository KinsonDigital/Velaptor, pull requests merged in 2023-11, with the labels that each got.

#787 🚧Replace custom guards
  Testing/VelaptorTests/Content/AtlasDataTests.cs
  Testing/VelaptorTests/Content/AtlasLoaderTests.cs
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Content/SoundLoaderTests.cs
  Testing/VelaptorTests/Content/TextureLoaderTests.cs
  Testing/VelaptorTests/Content/TextureTests.cs
  Testing/VelaptorTests/NativeInterop/FreeType/FreeTypeErrorEventArgsTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwErrorEventArgsTests.cs
  Testing/VelaptorTests/OpenGL/GLErrorEventArgsTests.cs
  Testing/VelaptorTests/OpenGL/GpuBufferNameAttributeTests.cs
  Testing/VelaptorTests/OpenGL/ShaderNameAttributeTests.cs
  Velaptor/Content/AtlasData.cs
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/Sound.cs
  Velaptor/Content/SoundLoader.cs
  Velaptor/Content/Texture.cs
  Velaptor/Content/TextureLoader.cs
  Velaptor/NativeInterop/FreeType/FreeTypeErrorEventArgs.cs
  Velaptor/NativeInterop/GLFW/GlfwErrorEventArgs.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/OpenGL/GLErrorEventArgs.cs
  Velaptor/OpenGL/GpuBufferNameAttribute.cs
  Velaptor/OpenGL/ShaderNameAttribute.cs
Labels: tech debt, low priority, preview

#792 🚧Improve factories
  Testing/AvaloniaTesting/OpenGLControl.cs
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/AnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/BackgroundManager.cs
  Testing/VelaptorTesting/Scenes/LayeredLineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredRectRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/NonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/ShapeScene.cs
  Testing/VelaptorTesting/Scenes/SoundScene.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTests/Content/ContentLoaderTests.cs
  Testing/VelaptorTests/ExtensionMethods/ContentExtensionsTests.cs
  Testing/VelaptorTests/Fakes/SceneBaseFake.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/Scene/SceneBaseTests.cs
  Testing/VelaptorTests/UI/ButtonTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/ContentLoader.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/IContentLoader.cs
  Velaptor/Content/Sound.cs
  Velaptor/Content/SoundLoader.cs
  Velaptor/Content/Texture.cs
  Velaptor/Content/TextureLoader.cs
  Velaptor/ExtensionMethods/ContentExtensions.cs
  Velaptor/Factories/ContentLoaderFactory.cs
  Velaptor/Factories/RendererFactory.cs
  Velaptor/Factories/UIControlFactory.cs
  Velaptor/Factories/WindowFactory.cs
  Velaptor/Graphics/Renderers/IRendererFactory.cs
  Velaptor/IoC.cs
  Velaptor/NativeInterop/FreeType/FreeTypeErrorEventArgs.cs
  Velaptor/NativeInterop/GLFW/GlfwErrorEventArgs.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/OpenGL/GLErrorEventArgs.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/OpenGL/GpuBufferNameAttribute.cs
  Velaptor/OpenGL/ShaderNameAttribute.cs
  Velaptor/Scene/IScene.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/UI/Button.cs
  Velaptor/UI/IWindow.cs
  Velaptor/UI/Label.cs
  Velaptor/UI/TextBox.cs
  Velaptor/UI/Window.cs
Labels: ✨new feature, tech debt, preview, on hold, 🧨breaking changes

#793 🚀Preview Release (v1.0.0-preview.30)
  .github/workflows/build-status-check.yml
  .github/workflows/unit-test-status-check.yml
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.30.md
  Velaptor.sln
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#800 🚧Replace custom guards
  Testing/VelaptorTests/Content/Caching/SoundCacheTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/Fonts/ContentFontPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/FontLoaderTests.cs
  Testing/VelaptorTests/Content/Fonts/FontPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/Services/FontStatsServiceTests.cs
  Testing/VelaptorTests/Content/Fonts/WindowsFontPathResolverTests.cs
  Testing/VelaptorTests/Content/TextureFactoryTests.cs
  Testing/VelaptorTests/Content/TextureTests.cs
  Velaptor/Content/Caching/SoundCache.cs
  Velaptor/Content/Caching/TextureCache.cs
  Velaptor/Content/Factories/TextureFactory.cs
  Velaptor/Content/Fonts/ContentFontPathResolver.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/Content/Fonts/FontPathResolver.cs
  Velaptor/Content/Fonts/Services/FontService.cs
  Velaptor/Content/Fonts/Services/FontStatsService.cs
  Velaptor/Content/Fonts/WindowsFontPathResolver.cs
  Velaptor/Content/Texture.cs
Labels: tech debt, low priority, preview

#780 🚧 Search and replace all equality checks with pattern matching
  Testing/AvaloniaTesting/ViewLocator.cs
  Velaptor/AppStats.cs
  Velaptor/InternalExtensionMethods.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
Labels: tech debt, low priority, preview

#795 🚧Replace custom guards
  Testing/VelaptorTests/Batching/BatchingManagerTests.cs
  Testing/VelaptorTests/Content/AtlasJSONDataPathResolverTests.cs
  Testing/VelaptorTests/Content/TexturePathResolverTests.cs
  Testing/VelaptorTests/Factories/NativeInputFactoryTests.cs
  Testing/VelaptorTests/Graphics/ImageLoaderTests.cs
  Testing/VelaptorTests/Graphics/RenderMediatorTests.cs
  Testing/VelaptorTests/Graphics/Renderers/FontRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/LineRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/ShapeRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/TextureRendererTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwDisplaysTests.cs
  Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
  Testing/VelaptorTests/Scene/SceneBaseTests.cs
  Velaptor/Batching/BatchingManager.cs
  Velaptor/Content/AtlasJSONDataPathResolver.cs
  Velaptor/Content/TexturePathResolver.cs
  Velaptor/Factories/NativeInputFactory.cs
  Velaptor/Graphics/ImageLoader.cs
  Velaptor/Graphics/RenderMediator.cs
  Velaptor/Graphics/Renderers/FontRenderer.cs
  Velaptor/Graphics/Renderers/LineRenderer.cs
  Velaptor/Graphics/Renderers/ShapeRenderer.cs
  Velaptor/Graphics/Renderers/TextureRenderer.cs
  Velaptor/NativeInterop/GLFW/GlfwDisplays.cs
  Velaptor/NativeInterop/OpenGL/OpenGLService.cs
  Velaptor/Scene/SceneBase.cs
Labels: tech debt, low priority, preview

#796 🚧Replace custom guards
  Testing/VelaptorTests/CachedValueTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/FontGpuBufferTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/GpuBufferBaseTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/LineGpuBufferTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/ShapeGpuBufferTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/TextureGpuBufferTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/OpenGL/Services/TextureShaderResourceLoaderServiceTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/FontShaderTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/LineShaderTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderProgramTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShapeShaderTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/TextureShaderTests.cs
  Testing/VelaptorTests/Services/AppSettingsServiceTests.cs
  Testing/VelaptorTests/Services/EventLoggerServiceTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Testing/VelaptorTests/Services/ImageServiceTests.cs
  Testing/VelaptorTests/Services/LoggingServiceTests.cs
  Testing/VelaptorTests/Services/SystemDisplayServiceTests.cs
  Velaptor/CachedValue.cs
  Velaptor/OpenGL/Buffers/GpuBufferBase.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/OpenGL/Services/TextureShaderResourceLoaderService.cs
  Velaptor/OpenGL/Shaders/FontShader.cs
  Velaptor/OpenGL/Shaders/LineShader.cs
  Velaptor/OpenGL/Shaders/ShaderProgram.cs
  Velaptor/OpenGL/Shaders/ShapeShader.cs
  Velaptor/OpenGL/Shaders/TextureShader.cs
  Velaptor/Services/AppSettingsService.cs
  Velaptor/Services/EventLoggerService.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/Services/ImageService.cs
  Velaptor/Services/LoggingService.cs
  Velaptor/Services/SystemDisplayService.cs
Labels: tech debt, low priority, preview

#817 🚧Update workflows to use preview infrastructure
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, 📦dependency update, preview

#819 🚧Fix deno permission issue
  .github/workflows/sync-status-check.yml
Labels: ♻️cicd, high priority, preview

#812 🚧Refactor FontAtlasMetrics to readonly record
  Testing/VelaptorTests/Graphics/FontAtlasMetricsTests.cs
  Velaptor/Graphics/FontAtlasMetrics.cs
  Velaptor/Services/FontAtlasService.cs
Labels: tech debt, medium priority, preview, 🏎️performance

#820 🚧Refactor GlyphMetrics to readonly record
  Testing/VelaptorTests/GameHelpersTests.cs
  Testing/VelaptorTests/Graphics/GlyphMetricsTests.cs
  Testing/VelaptorTests/Graphics/GraphicsExtensionMethodsTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Velaptor/Content/Fonts/Services/FontService.cs
  Velaptor/GameHelpers.cs
  Velaptor/Graphics/GlyphMetrics.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/UI/TextBox.cs
Labels: tech debt, medium priority, preview, 🧨breaking changes, 🏎️performance

#824 🚧Add permission to sync box workflow
  .github/workflows/sync-bot.yml
Labels: ♻️cicd, preview
