Repository KinsonDigital/Velaptor, pull requests merged in 2023-07, with the labels that each got.

#636 🚧Setup issue syncing system
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/sync-issue-to-pr.yml
Labels: ♻️cicd, high priority, preview

#637 🚧Change CICD setup for new branching model
  .config/dotnet-tools.json
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/sonar-scan-pr-status-check.yml
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
  .gitignore
  .nuke/parameters.json
  .vscode/release-notes.code-snippets
Labels: ♻️cicd, high priority, preview

#639 🚧Improve release workflows
  .github/workflows/build-pr-status-check.yml
  .github/workflows/release.yml
  .github/workflows/sync-bot-status-check.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
  .vscode/settings.json
Labels: ♻️cicd, high priority, preview

#644 🚧Create add to proj workflow
  .github/ReleaseTweetTemplate.txt
  .github/workflows/add-new-issue-to-project.yml
  Velaptor.sln
Labels: ♻️cicd, high priority, preview

#652 🐛Fix various bugs with textbox
  .github/stale.yml
  Velaptor.sln
  Velaptor/UI/TextBox.cs
  Velaptor/UI/TextCursor.cs
  Velaptor/UI/TextSelection.cs
Labels: 🐛bug, preview

#657 🚀Preview Release (v1.0.0-preview.23)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.23.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release
