Repository KinsonDigital/Velaptor, pull requests merged in 2023-06, with the labels that each got.

#618 🚧Setup renovate to use org level preset
  renovate.json
Labels: medium priority, preview, ⚙️config

#622 🚧Refactor unit test assertions
  Testing/VelaptorTests/Content/TextureLoaderTests.cs
  Testing/VelaptorTests/Content/TexturePathResolverTests.cs
  Testing/VelaptorTests/Content/TextureTests.cs
  Testing/VelaptorTests/Exceptions/EnumOutOfRangeExceptionTests.cs
  Testing/VelaptorTests/Exceptions/InvalidRenderEffectsExceptionTests.cs
Labels: good first issue, tech debt, medium priority, preview

#623 🚧Refactor unit test assertions
  Testing/VelaptorTests/Exceptions/LoadEmbeddedResourceExceptionTests.cs
  Testing/VelaptorTests/Exceptions/SystemDisplayExceptionTests.cs
  Testing/VelaptorTests/Graphics/AtlasSubTextureDataTests.cs
  Testing/VelaptorTests/Graphics/CornerRadiusTests.cs
  Testing/VelaptorTests/Graphics/FontAtlasMetricsTests.cs
Labels: good first issue, tech debt, medium priority, preview

#625 🚧Use null/empty string guard in GLInvoker methods
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
Labels: tech debt, low priority, preview
