Repository KinsonDigital/Velaptor, pull requests merged in 2023-12, with the labels that each got.

#821 🚧Refactor GlfwVideoMode to readonly struct
  Velaptor/NativeInterop/GLFW/GlfwInvoker.cs
  Velaptor/NativeInterop/GLFW/GlfwVideoMode.cs
Labels: tech debt, medium priority, preview, 🏎️performance

#842 🚧Update infrastructure
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sdk-status-check.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, 📦dependency update

#843 🚧Update to dotnet 8
  Performance/MeasureTextPerf/MeasureTextPerf.csproj
  Testing/AvaloniaTesting/AvaloniaTesting.csproj
  Testing/VelaptorTesting/VelaptorTesting.csproj
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/Velaptor.csproj
Labels: 📦dependency update, high priority, preview

#846 🚧Deprecate the UI controls
  Velaptor/UI/Button.cs
  Velaptor/UI/IControl.cs
  Velaptor/UI/ISizable.cs
  Velaptor/UI/Label.cs
  Velaptor/UI/TextBox.cs
Labels: tech debt, high priority, preview

#848 🚧Refactor KeyCodeExtension tests
  Testing/VelaptorTests/ExtensionMethods/KeyCodeExtensionsTests.cs
  Velaptor/ExtensionMethods/KeyCodeExtensions.cs
  Velaptor/Input/Enums.cs
Labels: tech debt, low priority, preview
