Repository KinsonDigital/Velaptor, pull requests merged in 2023-09, with the labels that each got.

#718 🚧Add ability to get monitor info
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/KeyboardScene.cs
  Testing/VelaptorTesting/Scenes/LayeredLineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredRectRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/MouseScene.cs
  Testing/VelaptorTesting/Scenes/NonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/ShapeScene.cs
  Testing/VelaptorTesting/Scenes/TextBoxScene.cs
  Testing/VelaptorTests/Exceptions/SystemDisplayExceptionTests.cs
  Testing/VelaptorTests/Hardware/SystemDisplayTests.cs
  Testing/VelaptorTests/Hardware/SystemMonitorTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwDisplayChangedEventArgsTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwDisplaysTests.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwErrorEventArgsTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Testing/VelaptorTests/Services/SystemDisplayServiceTests.cs
  Testing/VelaptorTests/Services/SystemMonitorServiceTests.cs
  Velaptor/Content/Fonts/Services/FontService.cs
  Velaptor/Exceptions/SystemDisplayException.cs
  Velaptor/Factories/HardwareFactory.cs
  Velaptor/Factories/InputFactory.cs
  Velaptor/Factories/WindowFactory.cs
  Velaptor/Hardware/SystemDisplay.cs
  Velaptor/Hardware/SystemMonitor.cs
  Velaptor/IoC.cs
  Velaptor/NativeInterop/GLFW/Enums.cs
  Velaptor/NativeInterop/GLFW/GlfwDisplayChangedEventArgs.cs
  Velaptor/NativeInterop/GLFW/GlfwDisplays.cs
  Velaptor/NativeInterop/GLFW/GlfwErrorEventArgs.cs
  Velaptor/NativeInterop/GLFW/GlfwInvoker.cs
  Velaptor/NativeInterop/GLFW/GlfwVideoMode.cs
  Velaptor/NativeInterop/GLFW/IDisplays.cs
  Velaptor/NativeInterop/GLFW/IGlfwInvoker.cs
  Velaptor/NativeInterop/GLFW/IMonitors.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/Services/FontAtlasService.cs
  Velaptor/Services/ISystemDisplayService.cs
  Velaptor/Services/ISystemMonitorService.cs
  Velaptor/Services/SystemDisplayService.cs
  Velaptor/Services/SystemMonitorService.cs
  Velaptor/UI/ControlBase.cs
Labels: ✨new feature, high priority, preview, 🧨breaking changes

#719 🚀Preview Release (v1.0.0-preview.25)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.25.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#723 🚧Add avalonia rendering
  .github/workflows/unit-test-status-check.yml
  Testing/AvaloniaTesting/App.axaml
  Testing/AvaloniaTesting/App.axaml.cs
  Testing/AvaloniaTesting/Assets/avalonia-logo.ico
  Testing/AvaloniaTesting/AvaloniaTesting.csproj
  Testing/AvaloniaTesting/Content/Graphics/velaptor-logo.png
  Testing/AvaloniaTesting/OpenGLControl.cs
  Testing/AvaloniaTesting/Program.cs
  Testing/AvaloniaTesting/RenderControl.axaml
  Testing/AvaloniaTesting/RenderControl.axaml.cs
  Testing/AvaloniaTesting/ViewLocator.cs
  Testing/AvaloniaTesting/ViewModels/MainWindowViewModel.cs
  Testing/AvaloniaTesting/ViewModels/ViewModelBase.cs
  Testing/AvaloniaTesting/Views/MainWindow.axaml
  Testing/AvaloniaTesting/Views/MainWindow.axaml.cs
  Testing/AvaloniaTesting/app.manifest
  Testing/AvaloniaTesting/stylecop.json
  Testing/VelaptorTesting/Scenes/AnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/KeyboardScene.cs
  Testing/VelaptorTesting/Scenes/LayeredLineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredRectRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/MouseScene.cs
  Testing/VelaptorTesting/Scenes/NonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/ShapeScene.cs
  Testing/VelaptorTesting/Scenes/SoundScene.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTests/Batching/BatcherTests.cs
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Exceptions/EnumOutOfRangeExceptionTests.cs
  Testing/VelaptorTests/Graphics/Renderers/FontRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/LineRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/ShapeRendererTests.cs
  Testing/VelaptorTests/Graphics/Renderers/TextureRendererTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/OpenGL/Services/TextureShaderResourceLoaderServiceTests.cs
  Testing/VelaptorTests/Scene/SceneBaseTests.cs
  Testing/VelaptorTests/Services/ImageServiceTests.cs
  Testing/VelaptorTests/UI/ControlBaseTests.cs
  Velaptor.sln
  Velaptor.sln.DotSettings
  Velaptor/App.cs
  Velaptor/Graphics/AvaloniaRenderContext.cs
  Velaptor/Graphics/IRenderContext.cs
  Velaptor/IoC.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/Scene/IScene.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/Scene/SceneManager.cs
  Velaptor/UI/TextBox.cs
Labels: ✨new feature, high priority

#724 🚧Refactor unit test assertions
  Performance/MeasureTextPerf/Program.cs
  Testing/AvaloniaTesting/App.axaml.cs
  Testing/AvaloniaTesting/AvaloniaTesting.csproj
  Testing/AvaloniaTesting/Program.cs
  Testing/AvaloniaTesting/RenderControl.axaml.cs
  Testing/AvaloniaTesting/ViewLocator.cs
  Testing/AvaloniaTesting/Views/MainWindow.axaml.cs
  Testing/VelaptorTests/Content/Fonts/FontTests.cs
  Testing/VelaptorTests/Helpers/TestDataLoader.cs
  Testing/VelaptorTests/NativeInterop/GLFW/GlfwErrorEventArgsTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/OpenGL/GpuBufferNameAttributeTests.cs
  Testing/VelaptorTests/OpenGL/OpenGLExtensionMethodsTests.cs
  Testing/VelaptorTests/OpenGL/ShaderNameAttributeTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderProgramTests.cs
  Testing/VelaptorTests/Services/ImageServiceTests.cs
  Velaptor.sln
  Velaptor/Services/FontAtlasService.cs
  Velaptor/UI/TextCursor.cs
Labels: good first issue, tech debt, medium priority, preview

#737 🚧Add ability to keep track of fps
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/TextBoxScene.cs
  Testing/VelaptorTests/Content/Factories/SoundFactoryTests.cs
  Testing/VelaptorTests/Graphics/Renderers/ShapeRendererTests.cs
  Testing/VelaptorTests/Helpers/TestsBase.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/Services/TimerServiceTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Velaptor/Content/SoundLoader.cs
  Velaptor/Content/TextureLoader.cs
  Velaptor/Factories/WindowFactory.cs
  Velaptor/IoC.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/Services/IStopWatchWrapper.cs
  Velaptor/Services/ITimerService.cs
  Velaptor/Services/StopWatchWrapper.cs
  Velaptor/Services/TimerService.cs
  Velaptor/UI/Button.cs
  Velaptor/UI/IWindow.cs
  Velaptor/UI/Label.cs
  Velaptor/UI/Window.cs
Labels: ✨new feature, high priority, preview, 🧨breaking changes

#740 🚀Preview Release (v1.0.0-preview.27)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.27.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#742 🚧Refactor unit test assertions
  Testing/VelaptorTests/Graphics/GlyphMetricsTests.cs
  Testing/VelaptorTests/Graphics/GraphicsExtensionMethodsTests.cs
  Testing/VelaptorTests/Graphics/ImageDataTests.cs
  Testing/VelaptorTests/Graphics/RectShapeTests.cs
  Velaptor/Graphics/GraphicsExtensionMethods.cs
Labels: good first issue, tech debt, medium priority, preview

#746 🚧Improve build and status check workflows
  .github/workflows/build-status-check.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, high priority, preview

#749 🚧Display funding options
  .github/FUNDING.yml
Labels: high priority, preview, 📝documentation/product
