Repository KinsonDigital/Velaptor, pull requests merged in 2023-02, with the labels that each got.

#499 🚧Pack XML docs into NuGet
  Velaptor/Velaptor.csproj
Labels: high priority, preview, 📝documentation/product

#500 🚧Refactor unit test assertions
  Testing/VelaptorTests/OpenGL/Exceptions/ShaderNotInitializedExceptionTests.cs
  Testing/VelaptorTests/OpenGL/GPUData/RectGPUDataTests.cs
  Testing/VelaptorTests/OpenGL/GPUData/RectVertexDataTests.cs
  Testing/VelaptorTests/OpenGL/GPUData/TextureGPUDataTesting.cs
  Testing/VelaptorTests/OpenGL/GPUData/TextureVertexDataTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/FontShaderTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/InternalExtensionMethods.cs
Labels: tech debt, medium priority, preview

#168 🚧Setup Codecov to collect code coverage data
  .github/workflows/prev-release.yml
  .github/workflows/prod-release.yml
  README.md
  Testing/VelaptorTests/VelaptorTests.csproj
Labels: tech debt, high priority, preview, on hold

#508 🚧Setup codacy
  .codacy.yml
  .github/workflows/prev-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .vscode/settings.json
  README.md
  Velaptor.sln
Labels: tech debt, high priority, preview

#513 🚧Setup dependabot
  .github/dependabot.yml
Labels: tech debt, medium priority, preview

#512 🚧Update workflows to use env files
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/unit-test-pr-status-check.yml
Labels: workflow, high priority, preview

#514 🚧Move and improve scene system to Velaptor
  Testing/VelaptorTesting/Core/SceneManager.cs
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Program.cs
  Testing/VelaptorTesting/Scenes/AnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/KeyboardScene.cs
  Testing/VelaptorTesting/Scenes/LayeredLineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredRectRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/MouseScene.cs
  Testing/VelaptorTesting/Scenes/NonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/RectangleScene.cs
  Testing/VelaptorTesting/Scenes/SoundScene.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTests/Exceptions/SceneAlreadyExistsExceptionTests.cs
  Testing/VelaptorTests/Fakes/SceneBaseFake.cs
  Testing/VelaptorTests/Fakes/WindowFake.cs
  Testing/VelaptorTests/FrameTimeTests.cs
  Testing/VelaptorTests/Helpers/MoqExtensions.cs
  Testing/VelaptorTests/OpenGL/Buffers/TextureGPUBufferTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/Scene/SceneBaseTests.cs
  Testing/VelaptorTests/Scene/SceneManagerTests.cs
  Testing/VelaptorTests/SizeUTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Content/Factories/SoundFactory.cs
  Velaptor/Content/Sound.cs
  Velaptor/Exceptions/EnumOutOfRangeException.cs
  Velaptor/Exceptions/InvalidRenderEffectsException.cs
  Velaptor/Exceptions/LoadEmbeddedResourceException.cs
  Velaptor/Exceptions/SceneAlreadyExistsException.cs
  Velaptor/Exceptions/SystemMonitorException.cs
  Velaptor/Factories/IReactableFactory.cs
  Velaptor/Factories/ReactableFactory.cs
  Velaptor/Factories/WindowFactory.cs
  Velaptor/FrameTime.cs
  Velaptor/IoC.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/ReactableData/WindowSizeData.cs
  Velaptor/Scene/IScene.cs
  Velaptor/Scene/ISceneManager.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/Scene/SceneManager.cs
  Velaptor/SizeU.cs
  Velaptor/UI/IWindow.cs
  Velaptor/UI/IWindowActions.cs
  Velaptor/UI/IWindowProps.cs
  Velaptor/UI/Window.cs
Labels: ✨new feature, high priority, preview, 🧨breaking changes, 🏎️performance

#518 🚧Refactor unit test assertions
  Testing/VelaptorTests/Content/Caching/SoundCacheTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/Exceptions/CachingExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/CachingMetaDataExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/LoadAtlasExceptionTests.cs
Labels: tech debt, medium priority, preview

#521 🚧Refactor unit test assertions
  Testing/VelaptorTests/Content/AtlasJSONDataPathResolverTests.cs
  Testing/VelaptorTests/Content/AtlasLoaderTests.cs
  Testing/VelaptorTests/Content/AtlasTexturePathResolverTests.cs
Labels: tech debt, medium priority, preview

#519 🚧Refactor unit test assertions
  Testing/VelaptorTests/Content/Caching/SoundCacheTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/Exceptions/CachingExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/CachingMetaDataExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/LoadAtlasExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/LoadFontExceptionTests.cs
  Testing/VelaptorTests/Content/Exceptions/LoadTextureExceptionTests.cs
  Testing/VelaptorTests/Content/Fonts/ContentFontPathResolverTests.cs
  Testing/VelaptorTests/Content/Fonts/Services/FontStatsServiceTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/UI/Window.cs
Labels: tech debt, medium priority, preview

#531 🚧Remove repo related documents
  CONTRIBUTING.md
  Documentation/Branching.md
  Documentation/EnvironmentSetup/LinuxDevEnvSetup.md
  Documentation/EnvironmentSetup/WindowsDevEnvSetup.md
  Documentation/Images/BranchingDiagram-DarkMode-v1.1.png
  Documentation/Images/BranchingDiagram-LightMode-v1.1.png
  Documentation/TableOfContents.md
  code_of_conduct.md
Labels: medium priority, preview, 📝documentation/product
