Repository KinsonDigital/Velaptor, pull requests merged in 2023-10, with the labels that each got.

#759 🚧Create unit tests for extension methods
  Testing/VelaptorTests/ExtensionMethods/KeyCodeExtensionsTests.cs
Labels: good first issue, tech debt, low priority, preview, 🍺hacktoberfest-easy

#758 🚧Create unit tests for extension methods
  Testing/VelaptorTests/ExtensionMethods/TextBoxExtensionsTests.cs
Labels: good first issue, tech debt, low priority, preview, 🍺hacktoberfest-easy

#761 🚧Refactor switch statements and out of range exceptions
  Testing/VelaptorTesting/ExtensionMethods.cs
  Testing/VelaptorTesting/Scenes/LayeredLineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredRectRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/ShapeScene.cs
  Testing/VelaptorTests/Batching/BatchingManagerTests.cs
  Testing/VelaptorTests/Exceptions/EnumOutOfRangeExceptionTests.cs
  Testing/VelaptorTests/ExtensionMethods/GpuDataTypeExtensionsTests.cs
  Testing/VelaptorTests/Helpers/Enums.cs
  Testing/VelaptorTests/Input/MouseStateTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
  Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
  Testing/VelaptorTests/OpenGL/Buffers/ShapeGpuBufferTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Velaptor/Batching/BatchingManager.cs
  Velaptor/Exceptions/EnumOutOfRangeException.cs
  Velaptor/ExtensionMethods/GpuDataTypeExtensions.cs
  Velaptor/Input/Mouse.cs
  Velaptor/Input/MouseState.cs
  Velaptor/NativeInterop/OpenGL/OpenGLService.cs
  Velaptor/OpenGL/Buffers/ShapeGpuBuffer.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/UI/TextBox.cs
Labels: tech debt, low priority

#765 🚧Refactor unit test assertions
  Testing/VelaptorTests/Input/KeyboardStateTests.cs
  Testing/VelaptorTests/Input/MouseStateTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
Labels: good first issue, tech debt, medium priority, preview, 🍺hacktoberfest-easy

#774 🚧Remove font load syntax requirements
  Testing/VelaptorTests/Batching/BatchingManagerTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/Fonts/FontLoaderTests.cs
  Testing/VelaptorTests/ExtensionMethods/GpuDataTypeExtensionsTests.cs
  Testing/VelaptorTests/Input/MouseStateTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
  Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Velaptor/Batching/BatchingManager.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/ExtensionMethods/GpuDataTypeExtensions.cs
  Velaptor/Input/Mouse.cs
  Velaptor/Input/MouseState.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/Services/FontMetaDataParseResult.cs
  Velaptor/Services/FontMetaDataParser.cs
Labels: tech debt, high priority, preview, 🧨breaking changes, 🦾enhancement

#775 🚀Preview Release (v1.0.0-preview.29)
  .vscode/release-notes.code-snippets
  .vscode/settings.json
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.29.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#777 🚧Update sync workflow
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  .github/workflows/sonar-scan-pr-status-check.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, medium priority, preview
