Repository KinsonDigital/Velaptor, pull requests merged in 2023-08, with the labels that each got.

#671 🚧Adjust release workflow input
  .github/workflows/release.yml
Labels: ♻️cicd, low priority, preview

#679 🚧Lock version of MOQ
  .github/workflows/sync-bot.yml
  Performance/MeasureTextPerf/MeasureTextPerf.csproj
  README.md
  Testing/VelaptorTests/VelaptorTests.csproj
Labels: 📦dependency update, high priority

#681 🚧Fix workflows
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/prepare-release.yml
Labels: ♻️cicd, medium priority, preview, 📝documentation/product

#688 🚧Create custom shader exceptions
  Testing/VelaptorTests/OpenGL/Exceptions/ShaderCompileExceptionTests.cs
  Testing/VelaptorTests/OpenGL/Exceptions/ShaderLinkExceptionTests.cs
  Testing/VelaptorTests/OpenGL/Shaders/ShaderProgramTests.cs
  Velaptor/OpenGL/Exceptions/ShaderCompileException.cs
  Velaptor/OpenGL/Exceptions/ShaderLinkException.cs
  Velaptor/OpenGL/Shaders/ShaderProgram.cs
Labels: good first issue, tech debt, medium priority, preview

#689 🚧Remove interface
  Velaptor/Content/IContentUnloadable.cs
Labels: good first issue, tech debt, preview

#696 🚧Prevent auto rendering with no scenes
  Testing/VelaptorTesting/MainWindow.cs
  Testing/VelaptorTesting/Scenes/AnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/BackgroundManager.cs
  Testing/VelaptorTesting/Scenes/KeyboardScene.cs
  Testing/VelaptorTesting/Scenes/LayeredTextureRenderingScene.cs
  Testing/VelaptorTesting/Scenes/LineRenderingScene.cs
  Testing/VelaptorTesting/Scenes/MouseScene.cs
  Testing/VelaptorTesting/Scenes/NonAnimatedGraphicsScene.cs
  Testing/VelaptorTesting/Scenes/ShapeScene.cs
  Testing/VelaptorTesting/Scenes/SoundScene.cs
  Testing/VelaptorTesting/Scenes/TextBoxScene.cs
  Testing/VelaptorTesting/Scenes/TextRenderingScene.cs
  Testing/VelaptorTests/Fakes/WindowFake.cs
  Testing/VelaptorTests/Scene/SceneManagerTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Scene/ISceneManager.cs
  Velaptor/Scene/SceneManager.cs
  Velaptor/UI/Window.cs
Labels: ✨new feature, tech debt, high priority, preview

#699 🚧Setup auto release of vel docs
  .github/cicd/.vscode/launch.json
  .github/cicd/.vscode/settings.json
  .github/cicd/scripts/trigger-api-docs-release.ts
  .github/workflows/release.yml
  .vscode/settings.json
  .vscode/workflow.code-snippets
  Testing/.vscode/settings.json
  Velaptor.code-workspace
  deno.json
  deno.lock
Labels: ♻️cicd, high priority, preview

#700 🚀Preview Release (v1.0.0-preview.24)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.24.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#706 🚧Adjust workflow triggers
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/sonar-scan-pr-status-check.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/unit-test-status-check.yml
Labels: ♻️cicd, high priority, preview

#713 🚧Fix shutting down issue
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Velaptor/OpenGL/GLWindow.cs
Labels: 🐛bug, high priority, preview
