Repository KinsonDigital/Velaptor, pull requests merged in 2024-01, with the labels that each got.

#854 🚀Preview Release (v1.0.0-preview.31)
  .vscode/settings.json
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.31.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#857 🚧Refactor FontStats to readonly record
  Testing/VelaptorTests/Content/Fonts/FontStatsTests.cs
  Velaptor/Content/Fonts/FontStats.cs
Labels: tech debt, medium priority, preview, 🏎️performance

#861 🚧Improve OpenGL buffering
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/NativeInterop/OpenGL/IGLInvoker.cs
Labels: low priority, preview, 🏎️performance

#884 🚧Refactor moq code to nsubstitute
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor.sln.DotSettings
  Velaptor/OpenGL/GLWindow.cs
Labels: 🐛bug, tech debt, medium priority

#886 🚀Preview Release (v1.0.0-preview.32)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.32.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#885 Add Repo-rater badge
  README.md
Labels: low priority, 📝documentation/product
