Repository KinsonDigital/Velaptor, pull requests merged in 2024-05, with the labels that each got.

#960 🚧Fix unload content issue
  Testing/VelaptorTests/Fakes/WindowFake.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor.sln.DotSettings
  Velaptor/IoC.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/UI/Window.cs
Labels: 🐛bug, high priority

#962 🚧Refactor moq code to nsubstitute
  Testing/VelaptorTests/Batching/BatchingManagerTests.cs
  Testing/VelaptorTests/Services/FontAtlasServiceTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Content/Fonts/Font.cs
  Velaptor/OpenGL/GLWindow.cs
Labels: tech debt, high priority

#963 🚀Preview Release (v1.0.0-preview.36)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.36.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release

#968 🚧Add resize capture in scenes
  Testing/VelaptorTests/Scene/SceneBaseTests.cs
  Testing/VelaptorTests/Scene/SceneManagerTests.cs
  Velaptor/Scene/IScene.cs
  Velaptor/Scene/ISceneManager.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/Scene/SceneManager.cs
  Velaptor/UI/Window.cs
Labels: ✨new feature, medium priority, preview
