Repository KinsonDigital/Velaptor, pull requests merged in 2024-04, with the labels that each got.

#932 🚧Update dependency KinsonDigital.Carbonate to v1.0.0-preview.18
  Performance/KeyboardPerf/PushReactableFake.cs
  Performance/MousePerf/PushReactableFake.cs
  Testing/VelaptorTesting/Scenes/AnimatedGraphicsScene.cs
  Testing/VelaptorTesting/UI/Control.cs
  Testing/VelaptorTests/Batching/BatcherTests.cs
  Testing/VelaptorTests/Batching/BatchingManagerTests.cs
  Testing/VelaptorTests/Content/Caching/SoundCacheTests.cs
  Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
  Testing/VelaptorTests/Content/Factories/SoundFactoryTests.cs
  Testing/VelaptorTests/Graphics/RenderMediatorTests.cs
  Testing/VelaptorTests/OpenGL/GLWindowTests.cs
  Testing/VelaptorTests/VelaptorTests.csproj
  Velaptor/App.cs
  Velaptor/Batching/Batcher.cs
  Velaptor/Batching/BatchingManager.cs
  Velaptor/Content/Caching/SoundCache.cs
  Velaptor/Content/Caching/TextureCache.cs
  Velaptor/Content/Factories/SoundFactory.cs
  Velaptor/Content/Sound.cs
  Velaptor/Content/Texture.cs
  Velaptor/Graphics/AvaloniaRenderContext.cs
  Velaptor/Graphics/RenderMediator.cs
  Velaptor/Graphics/Renderers/FontRenderer.cs
  Velaptor/Graphics/Renderers/LineRenderer.cs
  Velaptor/Graphics/Renderers/ShapeRenderer.cs
  Velaptor/Graphics/Renderers/TextureRenderer.cs
  Velaptor/Input/Mouse.cs
  Velaptor/NativeInterop/OpenGL/GLInvoker.cs
  Velaptor/OpenGL/Buffers/FontGpuBuffer.cs
  Velaptor/OpenGL/Buffers/GpuBufferBase.cs
  Velaptor/OpenGL/Buffers/LineGpuBuffer.cs
  Velaptor/OpenGL/Buffers/ShapeGpuBuffer.cs
  Velaptor/OpenGL/Buffers/TextureGpuBuffer.cs
  Velaptor/OpenGL/GLWindow.cs
  Velaptor/OpenGL/Shaders/FontShader.cs
  Velaptor/OpenGL/Shaders/LineShader.cs
  Velaptor/OpenGL/Shaders/ShaderProgram.cs
  Velaptor/OpenGL/Shaders/ShapeShader.cs
  Velaptor/OpenGL/Shaders/TextureShader.cs
  Velaptor/Scene/SceneBase.cs
  Velaptor/Services/KeyboardDataService.cs
  Velaptor/UI/TextBox.cs
  Velaptor/UI/TextCursor.cs
  Velaptor/UI/TextSelection.cs
  Velaptor/Velaptor.csproj
  create-pr.ps1
Labels: 📦dependency update, preview

#939 🚧Improve and update content API
  Velaptor/Content/AtlasData.cs
  Velaptor/Content/AtlasLoader.cs
  Velaptor/Content/AudioLoader.cs
  Velaptor/Content/Fonts/FontLoader.cs
  Velaptor/Content/TextureLoader.cs
Labels: high priority, preview, 🧨breaking changes, api changes

#911 🚧Replace custom guards
  Testing/VelaptorTests/Content/AudioPathResolverTests.cs
  Testing/VelaptorTests/Content/Factories/AudioFactoryTests.cs
  Testing/VelaptorTests/Content/Factories/FontFactoryTests.cs
  Testing/VelaptorTests/Guards/EnsureThatTests.cs
  Testing/VelaptorTests/Hardware/SystemDisplayTests.cs
  Testing/VelaptorTests/Input/KeyboardTests.cs
  Testing/VelaptorTests/Input/MouseTests.cs
  Testing/VelaptorTests/UI/WindowTests.cs
  Velaptor/Content/AudioPathResolver.cs
  Velaptor/Content/Factories/AudioFactory.cs
  Velaptor/Content/Factories/FontFactory.cs
  Velaptor/Guards/EnsureThat.cs
  Velaptor/Hardware/SystemDisplay.cs
  Velaptor/Input/Keyboard.cs
  Velaptor/Input/Mouse.cs
  Velaptor/UI/Button.cs
  Velaptor/UI/Label.cs
  Velaptor/UI/Window.cs
Labels: tech debt, low priority, preview

#943 🚧Refactor moq code to nsubstitute
  Testing/VelaptorTests/Content/Caching/AudioCacheTests.cs
Labels: tech debt, high priority

#945 🚧Remove deprecated controls
  Testing/VelaptorTests/ExtensionMethods/TextBoxExtensionsTests.cs
  Testing/VelaptorTests/Fakes/ControlBaseFake.cs
  Testing/VelaptorTests/UI/ControlBaseTests.cs
  Testing/VelaptorTests/UI/LabelTests.cs
  Testing/VelaptorTests/UI/TextCursorTests.cs
  Velaptor/ExtensionMethods/TextBoxExtensions.cs
  Velaptor/Factories/IUIControlFactory.cs
  Velaptor/Factories/IUIDependencyFactory.cs
  Velaptor/Factories/UIControlFactory.cs
  Velaptor/Factories/UIDependencyFactory.cs
  Velaptor/IoC.cs
  Velaptor/ReactableData/TextBoxStateData.cs
  Velaptor/UI/Button.cs
  Velaptor/UI/ControlBase.cs
  Velaptor/UI/Enums.cs
  Velaptor/UI/IControl.cs
  Velaptor/UI/ISizable.cs
  Velaptor/UI/ITextCursor.cs
  Velaptor/UI/ITextSelection.cs
  Velaptor/UI/Label.cs
  Velaptor/UI/TextBox.cs
  Velaptor/UI/TextCursor.cs
  Velaptor/UI/TextSelection.cs
Labels: tech debt, preview, 🧨breaking changes

#948 🚧Removed public ctors from Texture
  Testing/VelaptorTests/Content/TextureTests.cs
  Velaptor/Content/Texture.cs
Labels: high priority, preview, 🧨breaking changes, api changes

#949 🚀Preview Release (v1.0.0-preview.35)
  ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.35.md
  Velaptor/Velaptor.csproj
Labels: 🚀Preview Release
